### ISSUE TITLE
setsketch?

### ISSUE THREAD

**Issue by jianshu93** [tabac/hyperloglog.rs#17]
Hello Hyperloglog team,
It seems setsketch paper is out and there are some improvement over the old implenmentation. see here: https://vldb.org/pvldb/vol14/p2244-ertl.pdf

Thanks,

Jianshu

**Comment by tabac** [comment]
👋 Great suggestion, as I mention in https://github.com/tabac/hyperloglog.rs/issues/18, I will add to my TODO list :)
